<a href="https://colab.research.google.com/github/Tejaswarreddy/talentbattleml/blob/main/Spam_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split      
from google.colab import files 

In [5]:
files.upload()

Saving spam.csv to spam.csv


In [6]:
df=pd.read_csv("spam.csv",encoding="latin-1")

In [7]:
df.head()

class                                            message Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [8]:
df.shape

(5572, 5)

In [9]:
#to check whether the target label is binary or not.
print(np.unique(df["class"]))

['ham' 'spam']


In [10]:
np.unique(df["message"])

array([' &lt;#&gt;  in mca. But not conform.',
       ' &lt;#&gt;  mins but i had to stop somewhere first.',
       ' &lt;DECIMAL&gt; m but its not a common car here so its better to buy from china or asia. Or if i find it less expensive. I.ll holla',
       ..., 'ÌÏ thk of wat to eat tonight.', 'ÌÏ v ma fan...',
       'ÌÏ wait 4 me in sch i finish ard 5..'], dtype=object)

In [11]:
#we have to create a sparse matrix

x=df["message"].values
y=df["class"].values

#creating countvectorizer object
cv=CountVectorizer()
x=cv.fit_transform(x)
sparse_matrix=x.toarray()
print(sparse_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
#shifting columns to apply target attribute i.e class
df.insert(0,"message",df.pop("message"))
df

message class Unnamed: 2  \
0     Go until jurong point, crazy.. Available only ...   ham        NaN   
1                         Ok lar... Joking wif u oni...   ham        NaN   
2     Free entry in 2 a wkly comp to win FA Cup fina...  spam        NaN   
3     U dun say so early hor... U c already then say...   ham        NaN   
4     Nah I don't think he goes to usf, he lives aro...   ham        NaN   
...                                                 ...   ...        ...   
5567  This is the 2nd time we have tried 2 contact u...  spam        NaN   
5568              Will Ì_ b going to esplanade fr home?   ham        NaN   
5569  Pity, * was in mood for that. So...any other s...   ham        NaN   
5570  The guy did some bitching but I acted like i'd...   ham        NaN   
5571                         Rofl. Its true to its name   ham        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [37]:
#Splitting the dataset into two splits Training and Test splits as in the ratio of 3:1
#x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.25,random_state=41)
x_train=x[:4180]
y_train=y[:4180]
x_test=x[4180:]
y_test=y[4180:]

In [38]:
#binarization to convert all values of dataset into Binary format
bnb=BernoulliNB(binarize=0.0)
model=bnb.fit(x_train,y_train)

y_pred_train=bnb.predict(x_train)
y_pred_test=bnb.predict(x_test)


In [39]:
#training score
print(bnb.score(x_train,y_train)*100)

#testing score
print(bnb.score(x_test,y_test)*100)

98.70813397129187
98.20402298850574


In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99      3615
        spam       0.99      0.91      0.95       565

    accuracy                           0.99      4180
   macro avg       0.99      0.95      0.97      4180
weighted avg       0.99      0.99      0.99      4180



In [41]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      1210
        spam       0.99      0.87      0.93       182

    accuracy                           0.98      1392
   macro avg       0.99      0.93      0.96      1392
weighted avg       0.98      0.98      0.98      1392

